### ISSUE TITLE
NullPointerException: 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference

### ISSUE THREAD

**Issue by secondVISION** [apache/cordova-android#1002]
# Bug Report

### What is expected to happen?
Cordova should silently exit.

### What does actually happen?
Cordova crashes because the parent Activity is not alive anymore

## Information

Start a CordovaWebview and load a slow/large website.

`cordovaWebView.loadUrl(url)`

If you return to the previous activity (by using the (hardware) back button), cordova will try to execute `cordova.getActivity().runOnUiThread()`, but the activity is no longer there.

e.g., https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaWebViewImpl.java#L187

Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at org.apache.cordova.CordovaWebViewImpl$2.run(CordovaWebViewImpl.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

### Command or Code

See information above on how to reproduce.

### Environment, Platform, Device

Android / All devices / All OS

### Version information

Android Studio 
Cordova 8.1.0

## Checklist

- [X] I searched for existing GitHub issues:
    Found issue: https://github.com/apache/cordova-android/issues/884 but this was closed due to lack of information
- [X] I updated all Cordova tooling to most recent version:
    Crash occured on 
    'org.apache.cordova:cordova:6.2.3'
    Updated to (crashed as well):
    'org.apache.cordova:framework:8.1.0'
- [X] I included all the necessary information above

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jaeheonshim** [comment]
You should be able to replicate the problem by enabling the "Don't keep activities" option in Android Developer Options (Developer options => Apps => Don't keep activities (Destroy every activity as soon as the user leaves it.)

**Comment by breautek** [comment]
When doing that on the android simulator, I run into a different crash stacktrace

```
D/CordovaActivity: Paused the activity.
D/CordovaActivity: Stopped the activity.
D/CordovaActivity: CordovaActivity.onDestroy()
D/CordovaWebViewImpl: >>> loadUrl(about:blank)
W/cr_AwContents: WebView.destroy() called while WebView is still attached to window.
W/cr_AwContents: Application attempted to call on a destroyed WebView
    java.lang.Throwable
        at org.chromium.android_webview.AwContents.t(chromium-TrichromeWebViewGoogle.apk-stable-410404481:2)
        at Mt.loadingStateChanged(chromium-TrichromeWebViewGoogle.apk-stable-410404481:2)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (5916) crash detected (code -1).
```

Maybe this depends on the API level of the device and/or the installed chrome version though. It kinda seems related.

**Comment by secondVISION** [comment]
Created a sample app: https://github.com/secondVISION/cordova-android-crash

How to reproduce:
- Click on "Start Cordova"
- Immediately press the Back key
- Wait on crash. Cordova will try to load the website in an activity which has already been destroyed.
  - Waiting can take up to 30 seconds I've noticed

Crash log:
```
2020-07-16 14:06:20.618 19256-19392/com.example.cordovacrash D/EGL_emulation: eglMakeCurrent: 0x8c152aa0: ver 3 0 (tinfo 0x8859b8c0)
2020-07-16 14:06:39.652 19256-19383/com.example.cordovacrash E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.example.cordovacrash, PID: 19256
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
        at org.apache.cordova.CordovaWebViewImpl$2.run(CordovaWebViewImpl.java:181)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-07-16 14:06:39.819 19256-19310/com.example.cordovacrash D/EGL_emulation: eglMakeCurrent: 0xa1305300: ver 3 0 (tinfo 0xa13031f0)
```

**Comment by secondVISION** [comment]
![cordovacrashgif](https://user-images.githubusercontent.com/8403152/87768592-aae51200-c81c-11ea-8b57-260b6131c09b.gif)
