### ISSUE TITLE
Downloaded Android(Ionic) app from play store shows keep stopping when trying to open the app

### ISSUE THREAD

**Issue by Govindvishnu** [apache/cordova-android#1003]
I have uploaded my updated apk in play store. Now it is in live. I just dowloaded my apk from play store and try to open it. It shows application keeps on stopping with following summary.  

E/AndroidRuntime: FATAL EXCEPTION: main
    
    java.lang.RuntimeException: Unable to create application com.gae.scaffolder.plugin.Application: com.gae.scaffolder.plugin.MessageGuardException_RFA6IDMwNA: DP: 304 (RmluZ2VycHJpbnQgMjAxOTA3MDIgWy4rKysrLl0gYXJtZWFiaS12N2E6YXJtZWFiaS12N2EgMjYvMi4xLjAvLSBtb3Rvcm9sYS9hbGkvYWxpOjguMC4wL09QUzI3LjgyLTQ1LzU2OnVzZXIvcmVsZWFzZS1rZXlz)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5838)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
     Caused by: com.gae.scaffolder.plugin.MessageGuardException_RFA6IDMwNA: DP: 304 (RmluZ2VycHJpbnQgMjAxOTA3MDIgWy4rKysrLl0gYXJtZWFiaS12N2E6YXJtZWFiaS12N2EgMjYvMi4xLjAvLSBtb3Rvcm9sYS9hbGkvYWxpOjguMC4wL09QUzI3LjgyLTQ1LzU2OnVzZXIvcmVsZWFzZS1rZXlz)
        at com.gae.scaffolder.plugin.Application.onCreate(Unknown Source:169)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1140)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5835)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6592) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769) 
     Caused by: java.lang.UnsatisfiedLinkError: DP: 304
        at com.gae.scaffolder.plugin.Application$Application.wuxig(Unknown Source:690)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.gae.scaffolder.plugin.Application$Application.Honlx(Unknown Source:99)
        at com.gae.scaffolder.plugin.Application$Application.loqunIlzz(Unknown Source:201)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.gae.scaffolder.plugin.Application.onCreate(Unknown Source:117)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1140) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5835) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6592) 

Edit 1: This app developed in ionic android

It not happened in local development, because once i complete my development, i have created signed release production build using ionic commands and checked in device. It worked well.

This issue happens only after i upload my app to play store, i download it and install but couldn't open due to crash.

Version: 
 cordova :8.0.0
cordova platfor : android6.3.0
ionic framework: ionicangular3.9.2
ionic : 3.20.0
npm:5.6.0
node:v8.11.1

Can anyone please help me? Thanks in advance

**Comment by breautek** [comment]
`android6.3.0` isn't a supported cordova-android platform, as it doesn't support API 28, which is required by Google Play store (I'm not sure how you even uploaded your apk tot he app store, unless if you have overridden the target SDK). You need at least `cordova-android@8`.

I'd start by upgrading the platform version... but based on the stacktrace, it appears to be crashing before cordova framework is executed, for the most part, assuming that `com.gae.scaffolder.plugin.Application` is your `CordovaActivity` class. If upgrading `cordova-android` does not work, then you'll need to provide a minimal reproduction app, without using ionic. (If you can't reproduce it without ionic, then this suggest the problem is within ionic).

**Comment by Govindvishnu** [comment]
Hi, Thanks ,
In this path com.gae.scaffolder.plugin.Application i have FCMPlugin and It's isntant id  class files.
If i remove fcm plugin, then the same error happens at cordova--plugin-notification folder.

**Comment by breautek** [comment]
Closing as stale.

But the issue appears to be related to third-party plugins, not with cordova-android.
