### ISSUE TITLE
After migrating to cordova android 9.0.0 app crashes on startup with NoClassDefFound

### ISSUE THREAD

**Issue by jachzen** [apache/cordova-android#1059]
# Bug Report

## Problem
App crashes on starup with NoClassDefFoundError

### What is expected to happen?

App is starting as expected

### What does actually happen?

App crashes with NoClassDefFoundError

## Information

I migrated my app (already using androidx) to cordova android 9. Compiling works fine but when I start the App it crashs with:

08-28 15:11:41.162 14735-14735/de.dff_solutions.hermesApp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.dff_solutions.hermesApp, PID: 14735
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/R$bool;
        at androidx.work.impl.WorkManagerImpl.<init>(WorkManagerImpl.java:174)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:147)
        at androidx.work.WorkManager.initialize(WorkManager.java:169)
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
        at android.app.ActivityThread.access$1600(ActivityThread.java:150)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.work.R$bool" on path: DexPathList[[zip file "/system/framework/com.symbol.emdk.jar", zip file "/data/app/de.dff_solutions.hermesApp-2/base.apk"],nativeLibraryDirectories=[/data/app/de.dff_solutions.hermesApp-2/lib/arm64, /data/app/de.dff_solutions.hermesApp-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at androidx.work.impl.WorkManagerImpl.<init>(WorkManagerImpl.java:174) 
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:147) 
        at androidx.work.WorkManager.initialize(WorkManager.java:169) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:5153) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: androidx.work.R$bool
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

### Environment, Platform, Device

Android

### Version information

Cli 9 and 10
Cordova android 9

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by breautek** [comment]
With the information available, it will be really hard to pinpoint the actual problem, but chances are, it's some combination of plugins that you're using.

We'll probably need a [sample reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) to provide more assistance.

**Comment by breautek** [comment]
Presumebly this was caused because of cordova-android@9. While cordova-android@9 had a flag to enable androidx, there was a lot of issues preventing it from working properly.

Cordova-android@10 has proper support for androidx.

Closing as stale.
