### ISSUE TITLE
Could not dispatch a message to the daemon. Cordova-android 9 only

### ISSUE THREAD

**Issue by sardapv** [apache/cordova-android#1065]
# Bug Report
I upgraded my project from cordova-android 8.1.0 to cordova-android 9.0.
Upgraded CLI to Cordova 9.
Upgraded Gradle to 6.5 (also updated in Env variable).

## Problem
My project is maven based, and is fully automated build, if I use cordova-android 8.1.0 , ionic cordova build android builds successfully, If I do with cordova-android 9.0, I see 'Could not dispatch a message to the daemon.'

### What is expected to happen?
Build Should be successful.

### What does actually happen?
Build fails with 'Could not dispatch a message to the daemon'

## Information

Please refer above.
Note: If I open the Android folder in Android Studio, then build it builds is successful.

### Command or Code

ionic cordova build android

### Environment, Platform, Device

Windows. Cordova 9.0. Gradle 6.5. Cordova-android 9.0

### Version information

Windows. Cordova 9.0. Gradle 6.5. Cordova-android 9.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version (dont wanna use cordova 10 cli, because of other bugs in ios)
- [x] I included all the necessary information above

**Comment by sardapv** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Could not dispatch a message to the daemon.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.launcher.daemon.client.DaemonConnectionException: Could not dispatch a message to the daemon.
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:69)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:35)
        at org.gradle.launcher.daemon.client.DaemonClientInputForwarder$ForwardTextStreamToConnection.endOfStream(DaemonClientInputForwarder.java:81)
        at org.gradle.launcher.daemon.client.InputForwarder$1.run(InputForwarder.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:812)
Caused by: org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:59252'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:140)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.dispatch(DaemonClientConnection.java:60)
        ... 9 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host.
        at sun.nio.ch.SocketDispatcher.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:63)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:105)
        at sun.nio.ch.IOUtil.write(IOUtil.java:63)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:485)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:279)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:267)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:261)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:138)
        ... 10 more


* Get more help at https://help.gradle.org

**Comment by sardapv** [comment]
I already tried `gradle --stop && gradle clean build` still same error

**Comment by sardapv** [comment]
Found the  problem, it  still is  a problem.
I have  IBM JDK also installed and in my env path. I used this

`cd platforms/android/ && gradlew.bat clean build  -Dorg.gradle.java.home="C:\Program Files\Android\Android Studio\jre"`

Now its success! Weird

**Comment by limzcode** [comment]
make sure you have this..... java.home="C:\Program Files\Android\Android Studio\jre"

**Comment by limzcode** [comment]
Just under  files  choose project structure  and configure it

**Comment by omar7efnawey** [comment]
> 

Please help me have the same problem 
could you please tell me as a beginner step by step

**Comment by pliniofm** [comment]
I have android@10.1.2 platform, Cordova CLI 11.0.0, and I have the same issue.
