### ISSUE TITLE
Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by micahlt** [apache/cordova-android#1066]
# Bug Report

### What is expected to happen?
I'm trying to build a Cordova platform for Android with Adaptive Icons.

### What does actually happen?
I get this error: 
```
Cannot read property 'startsWith' of undefined
TypeError: Cannot read property 'startsWith' of undefined
    at updateIconResourceForAdaptive (/media/file/Documents/Code/sc4-mobile/platforms/android/cordova/lib/prepare.js:475:24)
    at updateIcons (/media/file/Documents/Code/sc4-mobile/platforms/android/cordova/lib/prepare.js:402:23)
    at /media/file/Documents/Code/sc4-mobile/platforms/android/cordova/lib/prepare.js:64:9
    at _fulfilled (/media/file/Documents/Code/sc4-mobile/node_modules/q/q.js:854:54)
    at /media/file/Documents/Code/sc4-mobile/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/media/file/Documents/Code/sc4-mobile/node_modules/q/q.js:816:13)
    at /media/file/Documents/Code/sc4-mobile/node_modules/q/q.js:624:44
    at runSingle (/media/file/Documents/Code/sc4-mobile/node_modules/q/q.js:137:13)
    at flush (/media/file/Documents/Code/sc4-mobile/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

### Command or Code
```
cordova build android
```

### Environment, Platform, Device
Ubuntu 20.04.1.  Mac Pro 5,1.

### Version information

Cordova 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by micahlt** [comment]
Fixed this issue - by investigating the code Cordova uses to put together Adaptive icons, I discovered that **you must specify a DPI for it to work**.  This is, however, inconsistent with current Cordova documentation.

**Comment by breautek** [comment]
> Fixed this issue - by investigating the code Cordova uses to put together Adaptive icons, I discovered that **you must specify a DPI for it to work**. This is, however, inconsistent with current Cordova documentation.

Can you point me to that part of the documentation?

**Comment by micahlt** [comment]
https://cordova.apache.org/docs/en/9.x/config_ref/images.html#android claims that the `density` attribute is optional.
