### ISSUE TITLE
Exception in thread "main" java.io.IOException: Unable to tunnel through proxy.

### ISSUE THREAD

**Issue by cant-sing** [apache/cordova-android#1068]
C:\Users\varun\Desktop\demo>cordova build android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\varun\AppData\Local\Android\Sdk (DEPRECATED)
Using Android SDK: C:\Users\varun\AppData\Local\Android\Sdk
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Downloading https://services.gradle.org/distributions/gradle-6.5-all.zip

Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 405 Method Not Allowed"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2152)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:83)
        at org.gradle.wrapper.Download.download(Download.java:66)
        at org.gradle.wrapper.Install$1.call(Install.java:68)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Command failed with exit code 1: C:\Users\varun\Desktop\demo\platforms\android\gradlew cdvBuildDebug -b C:\Users\varun\Desktop\demo\platforms\android\build.gradle

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by cant-sing** [comment]
Actually I'm a student at Mumbai University, India. And I'm learning Cordova for mobile programming. I have a laptop of windows 10 64 bit and I've followed every step to install Cordova. But every time during building android I'm having this error... Can you please provide some solution??
 
The Things I've installed before installing Cordova: -
1- JAVA JDK and JRE(including setting their environmental path).
2- Node.js((including setting their environmental path).
3- Gradle(latest version and also set its environmental path).
4- Android studio(For virtual emulator).
5- Installed Cordova.
Afterward, I've created new project through this command in mew cmd- cordova create demo com.cordova.demo demo
Then I've added platform as android - cordova platforms add android
Then I've built the android- cordova build android
After the Build command I'm having that error...
Please help me out✌

**Comment by faugusztin** [comment]
Your internet has a network wide proxy, which is not allowing Gradle to use certain HTTP methods (probably CONNECT). There is nothing wrong on Gradle/Cordova side, it is your network which is blocking a request from Gradle. You need to configure it correctly in [Gradle configuration](https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy), but that might not be enough, and you might need to use a different internet connection without a proxy.
