### ISSUE TITLE
Unable to use cordova

### ISSUE THREAD

**Issue by Priyashittal** [apache/cordova-android#1071]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Admin>cordova -v
C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
'powershell' is not recognized as an internal or external command,
operable program or batch file.

    at makeError (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\windows-release\index.js:39:19)
    at osName (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\os-name\index.js:39:18)
    at new Insight (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\node_modules\insight\lib\index.js:37:13)
    at new RelentlessInsight (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\src\telemetry.js:31:1)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\cordova\src\telemetry.js:39:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 1,
  stdout: '',
  stderr: "'powershell' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n',
  failed: true,
  signal: null,
  cmd: 'powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption',
  timedOut: false
}

C:\Users\Admin>

**Comment by breautek** [comment]
Looks like you're missing `powershell` in your `PATH` environment variable.

Try adding `%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\` to your `PATH` variable.

Note that `WindowsPowerShell` version may differ, so you may want to look inside the folder to determine what version exists first.

Like with all environment variable changes, changes only apply on new terminal sessions, so make sure that you close and reopen the terminal when testing changes.

**Comment by jcesarmobile** [comment]
closing as it's not a cordova-android bug
