### ISSUE TITLE
cordova-android and npm@7 don't work together.

### ISSUE THREAD

**Issue by rodrigograca31** [apache/cordova-android#1090]
# Bug Report

I've been running the new npm version (7) and this is the first project that I had problems with.

## Problem

Running the following commands gives an error:
```
cordova platform remove android
cordova platform add android --verbose
```

### What is expected to happen?

Installation of `cordova-android@^9.0.0`

### What does actually happen?

```
No scripts found for hook "before_platform_add".
No version supplied. Retrieving version from config.xml...
Grabbing pinned version.
Using cordova-fetch for cordova-android@^9.0.0
fetch: Installing cordova-android@^9.0.0 to /home/unknown/git/REDACTED_PROJECT_DIR
Running command: npm install cordova-android@^9.0.0 --save-dev
Command finished with error code 0: npm install,cordova-android@^9.0.0,--save-dev
Failed to fetch platform cordova-android@^9.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: CordovaError: Could not determine package name from output:
added 48 packages, and audited 1015 packages in 4s

4 packages are looking for funding
  run `npm fund` for details

14 vulnerabilities (12 low, 1 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
CordovaError: Failed to fetch platform cordova-android@^9.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: CordovaError: Could not determine package name from output:
added 48 packages, and audited 1015 packages in 4s

4 packages are looking for funding
  run `npm fund` for details

14 vulnerabilities (12 low, 1 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
    at /home/unknown/npm/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform/addHelper.js:288:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Information
Like I stated before, its specific to npm 7, the new version that isn't out yet but its about to be
https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

### Command or Code

`npm i -g npm@next-7` followed by `cordova platform rm android && cordova platform add android --verbose`

### Environment, Platform, Device

```
Environment:

    OS: LinuxMint 20 (linux 5.4.0-48-generic) x64
    Node: v12.19.0
    npm: 7.0.0
```

### Version information

```
Cordova Packages:

    cli: 10.0.0
        common: 4.0.2
        create: 3.0.0
        lib: 10.0.0
            common: 4.0.2
            fetch: 3.0.0
            serve: 4.0.0
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Thanks for bringing attention to us.

This part of the codebase that handles fetching dependencies is actually part of `cordova-lib` so I'll be moving this ticket to that repo.

I've ran `npm test` on:

- cordova-android
- cordova-lib
- cordova-cli

Only `cordova-lib` fails on NPM 7, so it looks like the might be the main package that requires updating for NPM 7 support.
