### ISSUE TITLE
cordova.plugins.diagnostic causes ionic app to crash

### ISSUE THREAD

**Issue by nirmal98kumar** [apache/cordova-android#1442]
# Bug Report
Ionic App crash when video played using video html tag

## Problem
cordova.plugins.diagnostic plugin when used causes the crash

### What is expected to happen?
video should play normally in android app ( which is the case in ios and web)

### What does actually happen?
Whenever a page where video is displayed using the <video> html tag , it crashes the android app.

Following logs produced from android studio logcat when app crashes:

2022-05-31 16:07:08.152 20971-209713/com.moterum W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
at Zt.run(chromium-TrichromeWebViewGoogle.apk-stable-410410681:9)
2022-05-31 16:07:08.152 20971-20971/com.moterum W/System.err: at android.os.MessageQueue.nativePollOnce(Native Method)
2022-05-31 16:07:08.152 20971-20971/com.moterum W/System.err: at android.os.MessageQueue.next(MessageQueue.java:335)
2022-05-31 16:07:08.152 20971-20971/com.moterum W/System.err: at android.os.Looper.loop(Looper.java:183)
2022-05-31 16:07:08.152 20971-20971/com.moterum W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7656)
2022-05-31 16:07:08.152 20971-20971/com.moterum W/System.err: at java.lang.reflect.Method.invoke(Native Method)
2022-05-31 16:07:08.152 20971-20971/com.moterum W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
2022-05-31 16:07:08.153 20971-20971/com.moterum W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

2022-05-31 16:07:08.152 20971-20971/com.moterum A/chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
2022-05-31 16:07:08.152 20971-20971/com.moterum D/SERVER: Handling local request: https://localhost/assets/icons/favicon.png
2022-05-31 16:07:08.152 20971-20971/com.moterum A/libc: Fatal signal 5 (SIGTRAP), code -6 (SI_TKILL) in tid 13373 (com.moterum), pid 13373 (com.moterum)

### Command or Code

-

### Environment, Platform, Device

Device : Android Simulator , Any Android phone

### Version information

**Framework :** 
Ionic (Angular)  , CLI version : 6.9.1

**Cordova :** 
CLI version : 11.0.0

_Platform_
cordova-android : 10.1.2

_Plugins_
//Plugin causing issue
   cordova.plugins.diagnostic: 6.0.2

//Other plugins used
    "cordova-plugin-ionic-webview": "^5.0.0",
    "cordova-plugin-push": "0.0.1",
   "@havesource/cordova-plugin-push": "git+https://github.com/havesource/cordova-plugin-push.git",
    "cordova-open-native-settings": "1.5.2",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-androidx": "^1.0.2",
    "cordova-plugin-androidx-adapter": "^1.1.1",
    "cordova-plugin-app-launcher": "^0.4.0",
    "cordova-plugin-background-fetch": "^7.0.3",
    "cordova-plugin-background-mode": "^0.7.3",
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-ble-central": "^1.2.5",
    "cordova-plugin-calendar": "^5.1.5",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^2.2.1",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-insomnia": "^4.3.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",
    "cordova-plugin-market": "^1.2.0",
    "cordova-plugin-media-capture": "^3.0.3",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-queries-schemes": "^0.1.6",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-telerik-imagepicker": "^2.3.3",
    "cordova-plugin-x-socialsharing": "^5.6.4",
    "cordova-plugin-x-toast": "^2.7.2",

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by nirmal98kumar** [comment]
Thanks for quick understanding of the problem !

Regarding the Android Webview , it is the latest version that is causing the issue . After uninstalling updates from Play Store which brings the webview version to base version I guess , makes the app work fine without crash . 

I will try upgrading the versions of both cordova.plugins.diagnostic plugin and dependency @ionic-native/diagnostic which is used in our app.
