### ISSUE TITLE
Signed apk getting crash After upgrading to Cordova Android 11

### ISSUE THREAD

**Issue by toufiqpathan** [apache/cordova-android#1522]
# Bug Report

## Problem
Signed Apk getting crashed after permission dialog and splash screen. 

Note: Debug apk is working fine
### What is expected to happen?

It should work as debug apk

### What does actually happen?

Signed Apk getting crashed after permission dialog and splash screen

## Information
Android studio logcat
2022-11-29 08:57:23.754  1924-2298  OplusThermalStats       pid-1924                             E  Error getting package info: com.dashride.clients.kidcarapp
2022-11-29 08:57:24.284  3715-4061  AuthDialogHelper        pid-3715                             E  CheckNotificationCanBeSetSecond: check com.dashride.clients.kidcarapp , Notification master switch on, unable to pop dialog
2022-11-29 08:57:28.855  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; CpuFgTime = 0 ms; CpuBgTime = 0 ms.
2022-11-29 08:57:28.855  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; CpuKernelFgTime = 0 ms; CpuKernelBgTime = 0 ms.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; CpuUserFgTime = 0 ms ; CpuUserBgTime = 0 ms.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; CpuFgPower = 0.0 mAh.; CpuBgPower = 0.0 mAh.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; AlarmFgWakeupCount = 0; AlarmBgWakeupCount = 0
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; JobFgCount = 0; JobBgCount = 0; JobFgTime = 0; JobBgTime = 0
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; SyncFgCount = 0; SyncBgCount = 0; SyncFgTime = 0; SyncBgTime = 0
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; WakeLockFgTime = 0 ms; WakeLockFgPower = 0.0 mAh.; WakeLockBgTime = 0 ms; WakeLockBgPower = 0.0 mAh.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; ScreenFgTime = 628444 ms; ScreenFgPower = 13.981133322222222 mAh.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgWifiRxBytes = 0 Bytes; BgWifiRxBytes = 0 Bytes; FgWifiTxBytes = 0 Bytes; BgWifiTxBytes = 0 Bytes; FgWifiRxPackets = 0 ; BgWifiRxPackets = 0 ; FgWifiTxPackets = 0 ; BgWifiTxPackets = 0 ; FgWiFiScanTimeMs = 0 ; BgWiFiScanTimeMs = 0 ; FgWiFiBatchScanTimeMs = 0 ; BgWiFiBatchScanTimeMs = 0 
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgWifiRxPacketsPower = 0.0 mAh; BgWifiRxPacketsPower = 0.0 mAh; FgWifiTxPacketsPower = 0.0 mAh; BgWifiTxPacketsPower = 0.0 mAh; FgWifiScanPower = 0.0 mAh; BgWifiScanPower = 0.0 mAh; FgWifiBatchScanPower = 0.0 mAh; BgWifiBatchScanPower = 0.0 mAh; FgWiFiTotalPower = 0.0 mAh; BgWiFiTotalPower = 0.0 mAh.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgMobileRxBytes = 0 Bytes; BgMobileRxBytes = 0 Bytes; FgMobileTxBytes = 0 Bytes; BgMobileTxBytes = 0 Bytes; FgMobileRxPackets = 0 ; BgMobileRxPackets = 0 ; FgMobileTxPackets = 0 ; BgMobileTxPackets = 0 ; FgMobileActiveCount = 0 ; BgMobileActiveCount = 0 ; FgMobileActiveTime = 0 ; BgMobileActiveTime = 0 
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgMobileRxPacketsPower = 0.0 mAh; BgMobileRxPacketsPower = 0.0 mAh; FgMobileTxPacketsPower = 0.0 mAh; BgMobileTxPacketsPower = 0.0 mAh; FgMobileTotalPower = 0.0 mAh; BgMobileTotalPower = 0.0 mAh.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgGpsTime = 0 ms; BgGpsTime = 0 ms.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgGpsPower = 0.0 mAh; BgGpsPower = 0.0 mAh.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgSensorTime = 0 ms; BgSensorTime = 0 ms.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgSensorPower = 0.0 mAh; BgSensorPower = 0.0 mAh.
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgCameraTime = 0 ms; BgCameraTime = 0 ms
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgCameraPower = 0.0 mAh; BgCameraPower = 0.0 mAh
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgFlashLightTime = 0 ms; BgFlashLightTime = 0 ms
2022-11-29 08:57:28.856  3715-6426  Battery                 pid-3715                             E  AppStats: Uid = 12010; pkgName = com.dashride.clients.kidcarapp; FgFlashLightPower = 0.0 mAh; BgFlashLightPower = 0.0 mAh
2022-11-29 08:57:29.584 17446-18196 ients.kidcarap          pid-17446                            A  runtime.cc:676] Runtime aborting...
                                                                                                    runtime.cc:676] Dumping all threads without mutator lock held
                                                                                                    runtime.cc:676] All threads:
                                                                                                    runtime.cc:676] DALVIK THREADS (83):
                                                                                                    runtime.cc:676] "pool-30-thread-2" prio=5 tid=81 Runnable
                                                                                                    runtime.cc:676]   | group="" sCount=0 ucsCount=0 flags=0 obj=0x1341e210 self=0xb400007884d06c00
                                                                                                    runtime.cc:676]   | sysTid=18196 nice=0 cgrp=default sched=0/0 handle=0x7881f6bcb0
                                                                                                    runtime.cc:676]   | state=R schedstat=( 12348286 17411092 49 ) utm=0 stm=0 core=6 HZ=100
                                                                                                    runtime.cc:676]   | stack=0x7881e68000-0x7881e6a000 stackSize=1039KB
                                                                                                    runtime.cc:676]   | held mutexes= "abort lock" "mutator lock"(shared held)
                                                                                                    runtime.cc:676]   native: #00 pc 000000000053a6e0  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+128) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #01 pc 00000000006f0e04  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+236) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #02 pc 00000000006fe690  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+208) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #03 pc 0000000000364248  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+440) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #04 pc 00000000006fce30  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+280) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #05 pc 00000000006d7e98  /apex/com.android.art/lib64/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+212) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #06 pc 00000000006d2b84  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1016) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #07 pc 0000000000016ea8  /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+80) (BuildId: 420d56eac27a210c92900f3ddb760c86)
                                                                                                    runtime.cc:676]   native: #08 pc 0000000000016450  /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352) (BuildId: 420d56eac27a210c92900f3ddb760c86)
                                                                                                    runtime.cc:676]   native: #09 pc 0000000000445224  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1612) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #10 pc 0000000000434004  /apex/com.android.art/lib64/libart.so (art::JNI<false>::NewObject(_JNIEnv*, _jclass*, _jmethodID*, ...)+200) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #11 pc 0000000000440554  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #12 pc 0000000000209398  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #13 pc 0000000000b1b9b2  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (z1.b.c+30)
                                                                                                    runtime.cc:676]   native: #14 pc 000000000020b074  /apex/com.android.art/lib64/libart.so (nterp_helper+7540) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #15 pc 0000000000b1c1ae  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (z1.f.<init>+26)
                                                                                                    runtime.cc:676]   native: #16 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d307dc6adc4105b5e392ad710770385d)
2022-11-29 08:57:29.584 17446-18196 ients.kidcarap          pid-17446                            A  runtime.cc:676]   native: #17 pc 0000000000b1bb0c  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (z1.e.a+4)
                                                                                                    runtime.cc:676]   native: #18 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #19 pc 0000000000a9db92  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (io.sqlc.b.i+14)
                                                                                                    runtime.cc:676]   native: #20 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #21 pc 0000000000a9e438  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (io.sqlc.SQLitePlugin.j+124)
                                                                                                    runtime.cc:676]   native: #22 pc 000000000020a254  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #23 pc 0000000000a9e3a0  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (io.sqlc.SQLitePlugin.a)
                                                                                                    runtime.cc:676]   native: #24 pc 0000000000209398  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   at io.liteglue.SQLiteNDKNativeDriver.sqlc_db_open(Native method)
                                                                                                    runtime.cc:676]   at z1.b.c(SourceFile:2)
                                                                                                    runtime.cc:676]   at z1.f.<init>(SourceFile:4)
                                                                                                    runtime.cc:676]   at z1.e.a(unavailable:2)
                                                                                                    runtime.cc:676]   at io.sqlc.b.i(unavailable:7)
                                                                                                    runtime.cc:676]   at io.sqlc.SQLitePlugin.j(SourceFile:6)
                                                                                                    runtime.cc:676]   at io.sqlc.SQLitePlugin.a(unavailable:0)
                                                                                                    runtime.cc:676]   at io.sqlc.SQLitePlugin$d.run(SourceFile:1)
                                                                                                    runtime.cc:676]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    runtime.cc:676]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    runtime.cc:676]   at java.lang.Thread.run(Thread.java:1012)
                                                                                                    runtime.cc:676] 
                                                                                                    runtime.cc:676] "main" prio=10 tid=1 Native
                                                                                                    runtime.cc:676]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x7196ef70 self=0xb400007958412400
                                                                                                    runtime.cc:676]   | sysTid=17446 nice=-10 cgrp=default sched=0/0 handle=0x79f9d78500
                                                                                                    runtime.cc:676]   | state=S schedstat=( 1209613208 192327450 2045 ) utm=85 stm=35 core=7 HZ=100
                                                                                                    runtime.cc:676]   | stack=0x7fe7772000-0x7fe7774000 stackSize=8188KB
                                                                                                    runtime.cc:676]   | held mutexes=
                                                                                                    runtime.cc:676]   native: #00 pc 0000000000075f30  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32) (BuildId: bbbdeb7c87c74f1491f92c6e605095b0)
                                                                                                    runtime.cc:676]   native: #01 pc 000000000047cc80  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+140) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #02 pc 000000000075bbf8  /apex/com.android.art/lib64/libart.so (artJniMethodEnd+204) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #03 pc 000000000020facc  /apex/com.android.art/lib64/libart.so (art_jni_method_end+12) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   at android.os.MessageQueue.nativePollOnce(Native method)
                                                                                                    runtime.cc:676]   at android.os.MessageQueue.next(MessageQueue.java:339)
                                                                                                    runtime.cc:676]   at android.os.Looper.loopOnce(Looper.java:179)
                                                                                                    runtime.cc:676]   at android.os.Looper.loop(Looper.java:344)
                                                                                                    runtime.cc:676]   at android.app.ActivityThread.main(ActivityThread.java:8212)
                                                                                                    runtime.cc:676]   at java.lang.reflect.Method.invoke(Native method)
                                                                                                    runtime.cc:676]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    runtime.cc:676]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
                                                                                                    runtime.cc:676] 
                                                                                                    runtime.cc:676] "Signal Catcher" prio=10 tid=6 WaitingInMainSignalCatcherLoop
                                                                                                    runtime.cc:676]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x12cc0000 self=0xb400007940c1b000
2022-11-29 08:57:29.584 17446-18196 ients.kidcarap          pid-17446                            A  runtime.cc:676]   | held mutexes=
                                                                                                    runtime.cc:676]   native: #00 pc 0000000000075f30  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32) (BuildId: bbbdeb7c87c74f1491f92c6e605095b0)
                                                                                                    runtime.cc:676]   native: #01 pc 000000000047cc80  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+140) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #02 pc 0000000000486588  /apex/com.android.art/lib64/libart.so (art::Monitor::Wait(art::Thread*, art::ObjPtr<art::mirror::Object>, long, int, bool, art::ThreadState)+2520) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   at java.lang.Object.wait(Native method)
                                                                                                    runtime.cc:676]   - waiting on <0x0239d930> (a java.lang.Object)
                                                                                                    runtime.cc:676]   at java.lang.Object.wait(Object.java:442)
                                                                                                    runtime.cc:676]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:203)
                                                                                                    runtime.cc:676]   - locked <0x0239d930> (a java.lang.Object)
                                                                                                    runtime.cc:676]   at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:224)
                                                                                                    runtime.cc:676]   at Wj.run(chromium-TrichromeWebViewGoogle6432.aab-stable-530410534:3)
                                                                                                    runtime.cc:676] 
                                                                                                    runtime.cc:676] "pool-30-thread-1" prio=5 tid=37 TimedWaiting
                                                                                                    runtime.cc:676]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x12cc21f8 self=0xb400007943983800
                                                                                                    runtime.cc:676]   | sysTid=18058 nice=0 cgrp=default sched=0/0 handle=0x78b34e1cb0
                                                                                                    runtime.cc:676]   | state=S schedstat=( 13490262 8872657 22 ) utm=1 stm=0 core=6 HZ=100
                                                                                                    runtime.cc:676]   | stack=0x78b33de000-0x78b33e0000 stackSize=1039KB
                                                                                                    runtime.cc:676]   | held mutexes=
                                                                                                    runtime.cc:676]   native: #00 pc 0000000000075f34  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+36) (BuildId: bbbdeb7c87c74f1491f92c6e605095b0)
                                                                                                    runtime.cc:676]   native: #01 pc 000000000048771c  /apex/com.android.art/lib64/libart.so (art::ConditionVariable::TimedWait(art::Thread*, long, int)+252) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   native: #02 pc 0000000000486094  /apex/com.android.art/lib64/libart.so (art::Monitor::Wait(art::Thread*, art::ObjPtr<art::mirror::Object>, long, int, bool, art::ThreadState)+1252) (BuildId: d307dc6adc4105b5e392ad710770385d)
                                                                                                    runtime.cc:676]   at java.lang.Object.wait(Native method)
                                                                                                    runtime.cc:676]   - waiting on <0x0dee49a9> (a org.apache.cordova.CordovaWebViewImpl$2)
                                                                                                    runtime.cc:676]   at java.lang.Object.wait(Object.java:442)
                                                                                                    runtime.cc:676]   at org.apache.cordova.CordovaWebViewImpl$2.run(SourceFile:2)
                                                                                                    runtime.cc:676]   - locked <0x0dee49a9> (a org.apache.cordova.CordovaWebViewImpl$2)
                                                                                                    runtime.cc:676]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    runtime.cc:676]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    runtime.cc:676]   at java.lang.Thread.run(Thread.java:1012)
                                                                                                    runtime.cc:676] 
                                                                                                    runtime.cc:676] "TokenRefresher" prio=4 tid=40 Native
                                                                                                    runtime.cc:676]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x12cc2300 self=0xb4000079439d2800
                                                                                                    runtime.cc:676]   | sysTid=18061 nice=10 cgrp=default sched=0/0 handle=0x78b23d7cb0
                                                                                                    runtime.cc:676]   | state=S schedstat=( 1031510 785677 5 ) utm=0 stm=0 core=3 HZ=100
                                                                                                    runtime.cc:676]   | stack=0x78b22d4000-0x78b22d6000 stackSize=1039KB
                                                                                                    runtime.cc:676]   | held mutexes=
                                                                                                    runtime.cc:676]   native: #00 pc 00000000000cad6c  /apex/com.android.runtime/lib64/bionic/libc.so (__epoll_pwait+12) (BuildId: bbbdeb7c87c74f1491f92c6e605095b0)
                                                                                                    runtime.cc:676]   native: #01 pc 0000000000017ea8  /system/lib64/libutils.so (android::Looper::pollInner(int)+184) (BuildId: 35086774ccd6a31df507943fb218149a)
                                                                                                    runtime.cc:676]   native: #02 pc 0000000000017d84  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+116) (BuildId: 35086774ccd6a31df507943fb218149a)
                                                                                                    runtime.cc:676]   native: #03 pc 0000000000154f04  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+48) (BuildId: 0a3f50eaf6daea7090ba06720efb1840)
2022-11-29 08:57:30.662 18220-18220 DEBUG                   pid-18220                            A  Process name is com.dashride.clients.kidcarapp, not key_process
2022-11-29 08:57:30.662 18220-18220 DEBUG                   pid-18220                            A  Cmdline: com.dashride.clients.kidcarapp
2022-11-29 08:57:30.662 18220-18220 DEBUG                   pid-18220                            A  pid: 17446, tid: 18196, name: pool-30-thread-  >>> com.dashride.clients.kidcarapp <<<
2022-11-29 08:57:30.663 18220-18220 DEBUG                   pid-18220                            A        #08 pc 0000000000b1b9b2  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (z1.b.c+30)
2022-11-29 08:57:30.663 18220-18220 DEBUG                   pid-18220                            A        #10 pc 0000000000b1c1ae  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (z1.f.<init>+26)
2022-11-29 08:57:30.663 18220-18220 DEBUG                   pid-18220                            A        #12 pc 0000000000b1bb0c  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (z1.e.a+4)
2022-11-29 08:57:30.663 18220-18220 DEBUG                   pid-18220                            A        #14 pc 0000000000a9db92  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (io.sqlc.b.i+14)
2022-11-29 08:57:30.663 18220-18220 DEBUG                   pid-18220                            A        #16 pc 0000000000a9e438  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (io.sqlc.SQLitePlugin.j+124)
2022-11-29 08:57:30.663 18220-18220 DEBUG                   pid-18220                            A        #18 pc 0000000000a9e3a0  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (io.sqlc.SQLitePlugin.a+0)
2022-11-29 08:57:30.663 18220-18220 DEBUG                   pid-18220                            A        #20 pc 0000000000a9df00  /data/app/~~1m0Nfu1a4--h24ebb6_OwQ==/com.dashride.clients.kidcarapp-Q5CT6Py2IhiCJEesT_FI3A==/oat/arm64/base.vdex (io.sqlc.SQLitePlugin$d.run+24)

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by toufiqpathan** [comment]
@breautek  please help me out, i am stuck

**Comment by breautek** [comment]
I do not know what is happening, but it looks like a deadlock issue mainly inside your SQLite C library.

```
runtime.cc:676] at io.liteglue.SQLiteNDKNativeDriver.sqlc_db_open(Native method)
runtime.cc:676] at z1.b.c(SourceFile:2)
runtime.cc:676] at z1.f.(SourceFile:4)
runtime.cc:676] at z1.e.a(unavailable:2)
runtime.cc:676] at io.sqlc.b.i(unavailable:7)
runtime.cc:676] at io.sqlc.SQLitePlugin.j(SourceFile:6)
runtime.cc:676] at io.sqlc.SQLitePlugin.a(unavailable:0)
runtime.cc:676] at io.sqlc.SQLitePlugin$d.run(SourceFile:1)
runtime.cc:676] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
runtime.cc:676] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
runtime.cc:676] at java.lang.Thread.run(Thread.java:1012)
```

At least, your app crashes while it's attempting to open up an SQLite database.

This doesn't appear to be a bug with Cordova itself, so I'll be closing this ticket.

**Comment by toufiqpathan** [comment]
problem was related to proguard , i have removed proguard plugin, and its working fine now
