### ISSUE TITLE
Cordova-android 11 splash screen support for API 29-32

### ISSUE THREAD

**Issue by shramko** [apache/cordova-android#1565]
Hi guys
Our application use custom splash screen for android. It was realized on cordova android 10 and worked well for API 29-30. Now we updated to cordova 11.1.0 and cordova-android 11.0.0. We followed the instructions (https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/) and remove old splash screen plugin and add configuration to config.xml. Now our application works well on android API 31-32 but crashed on API 29-30 with below exception (logs from Android Studio). **Does it possible to support custom splash screen with cordova-android 11 and android API 29-30? If true, how to do it?**

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: qa, PID: 13770
    java.lang.RuntimeException: Unable to start activity ComponentInfo{qa/qa.MainActivity}: android.content.res.Resources$NotFoundException: Drawable qa:drawable/ic_cdv_splashscreen with resource ID #0x7f08008b
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.content.res.Resources$NotFoundException: Drawable qa:drawable/ic_cdv_splashscreen with resource ID #0x7f08008b
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_cdv_splashscreen.xml from drawable resource ID #0x7f08008b
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:891)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:673)
        at android.content.res.Resources.loadDrawable(Resources.java:993)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:983)
        at android.content.res.Resources.getDrawable(Resources.java:922)
        at android.content.res.Resources$Theme.getDrawable(Resources.java:1729)
        at androidx.core.splashscreen.SplashScreen$Impl.install(SplashScreen.kt:264)
        at androidx.core.splashscreen.SplashScreen.install(SplashScreen.kt:189)
        at androidx.core.splashscreen.SplashScreen.access$install(SplashScreen.kt:121)
        at androidx.core.splashscreen.SplashScreen$Companion.installSplashScreen(SplashScreen.kt:146)
        at androidx.core.splashscreen.SplashScreen.installSplashScreen(Unknown Source:2)
        at org.apache.cordova.CordovaActivity.onCreate(CordovaActivity.java:110)
        at qa.MainActivity.onCreate(MainActivity.java:31)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable
        at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:278)
        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:199)
        at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:144)
Disconnected from the target VM, address: 'localhost:52518', transport: 'socket'
E/AndroidRuntime:     at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
        at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1361)
        at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:954)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:877)

**Comment by breautek** [comment]
I'm not sure what you mean by custom splash screen but

> android.content.res.Resources$NotFoundException: Drawable qa:drawable/ic_cdv_splashscreen with resource ID #0x7f08008b

indicates that you're missing your drawable which when you prepare/build, it should be in your `<cordova-project>/platforms/android/app/src/main/res/drawable-nodpi/ic_cdv_splashscreen.png`. If you're using a vector, then I think it gets placed into `<cordova-project>/platforms/android/app/src/main/res/drawable/ic_cdv_splashscreen.xml` instead. Perhaps confirm that the file is indeed found in the expected locations.

Additionally if you're using an SVG vector, not all SVG features might be [supported](https://developer.android.com/studio/write/vector-asset-studio#svg-supported).

**Comment by breautek** [comment]
Closing as stale

**Comment by pramodpurushan77** [comment]
<preference name="AndroidWindowSplashScreenAnimatedIcon" value="resources/splash.png" />
        <preference name="AndroidWindowSplashScreenBackground" value="#ffffff" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />

for platform android,

do check  <preference /> are added in config file, you may replace AndroidWindowSplashScreenBackground value. without this line issue happens on devices  SDK below 31. 
Hope this one works for you as well
