### ISSUE TITLE
shelljs@0.8.x update in dependencies

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-android#771]
I think we should update this dependency if possible.

I tried this in my mac workarea, got the following error when I tried `npm test`:

```
Failures:
1) plugin add Test#001 : create project and add a plugin with framework
  Message:
    Expected Error: ENOTDIR: not a directory, open '/Users/brodybits/dev/cordova/cordova-android/test-com.test.plugin.framework/cordova-plugin-fake/framework-FakeLib/build.gradle' to be null. Tip: To check for deep equality, use .toEqual() instead of .toBe().
  Stack:
    Error: Expected Error: ENOTDIR: not a directory, open '/Users/brodybits/dev/cordova/cordova-android/test-com.test.plugin.framework/cordova-plugin-fake/framework-FakeLib/build.gradle' to be null. Tip: To check for deep equality, use .toEqual() instead of .toBe().
        at <Jasmine>
        at /Users/brodybits/dev/cordova/cordova-android/spec/e2e/plugin.spec.js:38:31
        at /Users/brodybits/dev/cordova/cordova-android/spec/e2e/helpers/projectActions.js:127:9
        at _rejected (/Users/brodybits/dev/cordova/cordova-android/test-com.test.plugin.framework/cordova/node_modules/q/q.js:864:24)
```

**Comment by brodybits** [comment]
Closing as I think we should migrate to fs-extra, instead.
