### ISSUE TITLE
Firebase Crashlytics:  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by gagapg** [apache/cordova-android#912]
# Bug Report
Hi all, 
I have an issue on Firebase Crash log,
Please help me check it, I am getting this crash frequently.
Thanks!

## Problem
*LinkedHashMap.java line 757, This issue has 44 crashes affecting 29 users (last 7 days)
```Fatal Exception: java.util.ConcurrentModificationException
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:785)
       at org.apache.cordova.PluginManager.postMessage(PluginManager.java:310)
       at org.apache.cordova.CordovaWebViewImpl.postMessage(CordovaWebViewImpl.java:381)
       at org.apache.cordova.splashscreen.SplashScreen$2.run(SplashScreen.java:166)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

*LinkedHashMap.java line 760, This issue has 44 crashes affecting 29 users (last 7 days)
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
       at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:788)
       at org.apache.cordova.PluginManager.postMessage(PluginManager.java:310)
       at org.apache.cordova.CordovaWebViewImpl.postMessage(CordovaWebViewImpl.java:381)
       at org.apache.cordova.splashscreen.SplashScreen$2.run(SplashScreen.java:166)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

*LinkedHashMap.java line 775
```
java.util.LinkedHashMap$LinkedHashIterator.nextNode (LinkedHashMap.java:775)
java.util.LinkedHashMap$LinkedValueIterator.next (LinkedHashMap.java:803)
org.apache.cordova.PluginManager.postMessage (PluginManager.java:310)
org.apache.cordova.CordovaWebViewImpl.postMessage (CordovaWebViewImpl.java:381)
org.apache.cordova.splashscreen.SplashScreen$2.run (SplashScreen.java:166)
android.os.Handler.handleCallback (Handler.java:888)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:213)
android.app.ActivityThread.main (ActivityThread.java:8147)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1101)
```

### Environment, Platform, Device
cordova-android 8.1.0
cordova-plugin-splashscreen 5.0.3 "Splashscreen"

Almost happens on Android 8+
Some devices:  Galaxy S8, S9+, Galaxy A7(2017), Note 9, Xperia XZ Premium,...

### Codes
![image](https://user-images.githubusercontent.com/57609479/73417127-9afa7400-4349-11ea-8d42-54a2ad761580.png)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment]
I've transferred this issue to cordova-android since the PluginManager file is maintained here. Also, it looks similar to #794

**Comment by gagapg** [comment]
Thank for update,
but I'm using the latest cordova-android version.
So do I need waiting for the next update of cordova-android?

**Comment by gagapg** [comment]
Hi,
Do you guys have any plans to fix it in the next release?

**Comment by HansKrywaa** [comment]
Same Crash appears to User with our App. I use `cordova-android@8.1.0`. Please fix!
